- hosts: all
  become: true
  tasks:
          - name: Apt update
            apt:
                    update_cache: yes
          - name: install pip
            apt:
                    name: python3-pip
                    state: latest
