apiVersion: v1
kind: Service
metadata:
  name: redirector
spec:
  selector:
    app: redirector 
  ports:
    - protocol: TCP
      port: 8000 
      targetPort: 8000
      nodePort: 32000 
  type: NodePort 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirector
  labels:
    app: redirector 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redirector
  template:
    metadata:
      labels:
        app: redirector
    spec:
      containers:
      - name: redirector
        image: pgnomme/redirector:latest
        ports:
        - containerPort: 8000
        env:
        - name: TARGET_URL
          value: "http://example.com"
        - name: PORT
          value: "8000"



