# Generated by Django 4.1.2 on 2023-01-03 11:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cabinets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet', models.IntegerField(unique=True)),
                ('hard', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(unique=True), size=None)),
            ],
        ),
    ]
