# Generated by Django 4.1.2 on 2023-01-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinets',
            name='cabinet',
            field=models.TextField(unique=True),
        ),
    ]
