# Generated by Django 4.1.2 on 2023-01-06 07:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_alter_cabinets_cabinet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabinets',
            old_name='hard',
            new_name='hardware_name',
        ),
        migrations.AddField(
            model_name='cabinets',
            name='hardware_number',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(unique=True), default=django.utils.timezone.now, size=None),
            preserve_default=False,
        ),
    ]
