# Generated by Django 4.1.2 on 2023-01-06 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_rename_hard_cabinets_hardware_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabinets',
            old_name='hardware_name',
            new_name='hard',
        ),
    ]
