# Generated by Django 4.1.2 on 2023-01-06 07:57

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_rename_hardware_name_cabinets_hard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinets',
            name='hard',
        ),
        migrations.AddField(
            model_name='cabinets',
            name='harware_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(unique=True), default=django.utils.timezone.now, size=None),
            preserve_default=False,
        ),
    ]
