# Generated by Django 4.1.2 on 2023-01-06 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_rename_harware_name_cabinets_hardware_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabinets',
            old_name='hardware_name',
            new_name='hard',
        ),
    ]
