# Generated by Django 4.1.2 on 2023-01-06 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_rename_hardware_name_cabinets_hard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinets',
            name='hardware_number',
        ),
    ]
