# Generated by Django 4.1.2 on 2023-01-06 08:04

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_remove_cabinets_hardware_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinets',
            name='hardware_number',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(unique=True), default=django.utils.timezone.now, size=None),
            preserve_default=False,
        ),
    ]
