# Generated by Django 4.1.2 on 2023-01-06 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0010_hardware_remove_cabinets_hard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Hardware', to='list.cabinets'),
        ),
    ]
